name: Release

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get version
        id: version
        run: |
          version=$(jq -r '.version' custom_components/configassistant/manifest.json)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Create zip file
        run: |
          cd custom_components
          zip -r ../configassistant.zip configassistant

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.version.outputs.version }}
          release_name: v${{ steps.version.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./configassistant.zip
          asset_name: configassistant.zip
          asset_content_type: application/zip
